(() => {
  const DEFAULT_QUESTIONS = [
    {id:1,left:{n:3,d:8},right:{n:10,d:12},answer:"<"},{id:2,left:{n:4,d:6},right:{n:4,d:10},answer:">"},{id:3,left:{n:9,d:14},right:{n:1,d:4},answer:">"},{id:4,left:{n:11,d:18},right:{n:7,d:16},answer:">"},{id:5,left:{n:17,d:20},right:{n:12,d:30},answer:">"},{id:6,left:{n:15,d:20},right:{n:3,d:8},answer:">"},{id:7,left:{n:4,d:8},right:{n:10,d:26},answer:">"},{id:8,left:{n:17,d:28},right:{n:1,d:5},answer:">"},{id:9,left:{n:6,d:15},right:{n:15,d:22},answer:"<"},{id:10,left:{n:6,d:10},right:{n:7,d:16},answer:">"},{id:11,left:{n:5,d:12},right:{n:15,d:24},answer:"<"},{id:12,left:{n:3,d:8},right:{n:11,d:10},answer:"<"},{id:13,left:{n:5,d:8},right:{n:7,d:14},answer:">"},{id:14,left:{n:5,d:6},right:{n:3,d:10},answer:">"}
  ];
  const state={questions:[],index:0,score:0,stars:0,attempts:0,usedHint:false,locked:false,correctCount:0};
  const $=id=>document.getElementById(id);
  const fractionText=f=>`${f.n} / ${f.d}`;
  function compare(a,b){const l=a.n*b.d,r=b.n*a.d;return l<r?"<":l>r?">":"=";}
  function compareToHalf(f){const t=2*f.n;return t<f.d?"< 1/2":t>f.d?"> 1/2":"= 1/2";}
  function makeBox(parent,{x,y,z=0,w,h,d=.035,color}){const el=document.createElement('a-box');el.setAttribute('position',`${x} ${y} ${z}`);el.setAttribute('width',w);el.setAttribute('height',h);el.setAttribute('depth',d);el.setAttribute('color',color);parent.appendChild(el);return el;}
  function drawFractionBars(q,reveal=false){const root=$('bars');while(root.firstChild)root.removeChild(root.firstChild);const trackWidth=2.35,trackHeight=.16;[{f:q.left,y:.18,color:'#FFB347'},{f:q.right,y:-.14,color:'#55C2A5'}].forEach(({f,y,color})=>{const startX=-trackWidth/2;makeBox(root,{x:0,y,w:trackWidth,h:trackHeight,color:'#E5EDF3'});if(reveal){const fillWidth=Math.max(.02,trackWidth*(f.n/f.d));makeBox(root,{x:startX+fillWidth/2,y,z:.035,w:fillWidth,h:trackHeight*.72,d:.05,color});}makeBox(root,{x:0,y,z:.075,w:.025,h:.25,d:.03,color:'#FF6B35'});});}
  function setText(id,value,color){const el=$(id);el.setAttribute('value',value);if(color)el.setAttribute('color',color);}
  function updateScore(){setText('score-text',`Stars: ${state.stars} | Score: ${state.score}`);}
  function renderQuestion(){const q=state.questions[state.index];state.attempts=0;state.usedHint=false;state.locked=false;setText('left-fraction',fractionText(q.left));setText('right-fraction',fractionText(q.right));setText('progress-text',`Question ${state.index+1} / ${state.questions.length}`);setText('hint-text','Use 1/2 as your benchmark','#557086');setText('status-text','Choose the correct symbol','#16324A');updateScore();drawFractionBars(q,false);}
  function playTone(kind){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return;const ctx=new Ctx(),now=ctx.currentTime,notes=kind==='correct'?[660,880]:kind==='finish'?[523,659,784]:[220,180];notes.forEach((frequency,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(.0001,now+i*.11);gain.gain.exponentialRampToValueAtTime(.12,now+i*.11+.01);gain.gain.exponentialRampToValueAtTime(.0001,now+i*.11+.10);osc.connect(gain).connect(ctx.destination);osc.start(now+i*.11);osc.stop(now+i*.11+.11);});}
  function awardStars(){if(state.usedHint)return 1;if(state.attempts===1)return 3;if(state.attempts===2)return 2;return 1;}
  function onAnswer(symbol){if(state.locked)return;const q=state.questions[state.index];state.attempts+=1;const correct=compare(q.left,q.right);if(symbol===correct){state.locked=true;state.correctCount+=1;const earned=awardStars();state.stars+=earned;state.score+=100+Math.max(0,40-(state.attempts-1)*20);updateScore();setText('status-text',`Correct!  +${earned} star${earned>1?'s':''}`,'#1B8F67');$('bunny').emit('bunnyHop');playTone('correct');window.setTimeout(()=>{state.index+=1;if(state.index>=state.questions.length)finishGame();else renderQuestion();},950);}else{setText('status-text','Try again — compare each fraction with 1/2','#C24B37');playTone('wrong');}}
  function showHint(){if(state.locked)return;const q=state.questions[state.index];state.usedHint=true;drawFractionBars(q,true);setText('hint-text',`${fractionText(q.left)} ${compareToHalf(q.left)}   |   ${fractionText(q.right)} ${compareToHalf(q.right)}`,'#2F80ED');}
  function finishGame(){state.locked=true;const total=state.questions.length,accuracy=Math.round((state.correctCount/total)*100);setText('progress-text','MISSION COMPLETE');setText('left-fraction','★');setText('right-fraction','★');setText('hint-text',`Accuracy ${accuracy}%  |  Total stars ${state.stars}`,'#2F80ED');setText('status-text',`Great job! Score ${state.score}`,'#1B8F67');drawFractionBars({left:{n:1,d:2},right:{n:1,d:2}},true);$('bunny').emit('bunnyHop');playTone('finish');document.querySelectorAll('.answer').forEach(el=>el.setAttribute('color','#EAF0F4'));}
  function bindInteractions(){document.querySelectorAll('.answer').forEach(el=>{el.addEventListener('click',()=>onAnswer(el.dataset.answer));el.addEventListener('mouseenter',()=>el.setAttribute('scale','1.06 1.06 1.06'));el.addEventListener('mouseleave',()=>el.setAttribute('scale','1 1 1'));});$('hint-button').addEventListener('click',showHint);$('hint-button').addEventListener('mouseenter',e=>e.currentTarget.setAttribute('scale','1.04 1.04 1.04'));$('hint-button').addEventListener('mouseleave',e=>e.currentTarget.setAttribute('scale','1 1 1'));}
  async function loadQuestions(){try{const r=await fetch('./data/questions.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(!Array.isArray(data)||!data.length)throw new Error('Question data is empty');return data;}catch(error){console.warn('Using embedded question fallback:',error);return DEFAULT_QUESTIONS;}}
  window.addEventListener('DOMContentLoaded',async()=>{state.questions=await loadQuestions();bindInteractions();renderQuestion();});
})();
